apply plugin: 'com.android.application'

android {
    compileSdk 34
    defaultConfig {
        applicationId 'com.fr3ts0n.androbd.plugin.csv'
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 10102
        versionName 'V1.1.2-API34'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    applicationVariants.configureEach { variant ->
        variant.resValue "string", "app_version", variant.versionName
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    productFlavors {
    }
    namespace 'com.fr3ts0n.androbd.plugin.csv'
    lint {
        abortOnError false
    }


}

dependencies {
    implementation project(':plugin')
}
