apply plugin: 'com.android.application'

android {
    compileSdk 34
    defaultConfig {
        applicationId 'com.fr3ts0n.androbd.plugin.sensorprovider'
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 10103
        versionName 'V1.1.3-API34'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    applicationVariants.configureEach { variant ->
        variant.resValue "string", "app_version", variant.versionName
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }


    productFlavors {
    }
    namespace 'com.fr3ts0n.androbd.plugin.sensorprovider'
    lint {
        abortOnError false
    }
}

dependencies {
    implementation project(':plugin')
}
